#!/usr/bin/env bash
# Atri Hegde (hegde-atri)
# https://github.com/hegde-atri/hegde-arch
#
# NAME: hegde-arch
# DESC: An Arch Linux post installation script
# WARNING: Run this script at your own risk!
# Dependencies: dialog

if [ "$(id -u)" = 0 ]; then
    echo "---------------------------------------------------------------------|"
    echo "|  This script MUST NOT be run as root user since it makes changes   |"
    echo "|     to the \$HOME directory of the \$USER executing this script.   |"
    echo "|    The \$HOME directory of the root user is, of course, '/root'.   |"
    echo "|    We don't want to mess around in there. So run this script as a  |"
    echo "| normal user. You will be asked for a sudo password when necessary. |"
    echo "----------------------------------------------------------------------"
    exit 1
fi

error() { \
    clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
}

echo "-------------------------------------------------"
echo "|      Installing dialog and syncing repos      |"
echo "-------------------------------------------------"
sudo pacman -Syu --noconfirm --needed dialog || error "Error syncing repos"

welcome(){ \
    printf '\033c'
    echo "-----------------------------------------------"
    echo "|           WELCOME TO HEGDE-ARCH             |"
    echo "-----------------------------------------------"
    echo "This is an arch linux post configuration script"
    echo "Make sure to stay at your computer for prompts "
    echo "-----------------------------------------------"
}

speedwarning(){ \
    echo "!! WARNING !!"
    echo "Parallel downloads not enabled in /etc/pacman.conf. This may result in a much slower installation"
}

distrowarning(){ \
    echo "!! WARNING !!"
    echo "This is not Arch linux"
}

grep -qs "#ParallelDownloads" /etc/pacman.conf && speedwarning
grep -qs "ID=arch" /etc/os-release || distrowarning

localewarning() { \
        [[ [[-z $LANG || -z $LC_CTYPE]] ]] && \
        echo "Locales not set properly, refer to the arch wiki, or reboot for change to take effect. Make sure that both LANG and LC_CTYPE have been set"
}

sudo nmcli connection modify wl01 ipv4.dns "9.9.9.9,1.1.1.1"
sudo nmcli connection modify eth0 ipv4.dns "9.9.9.9,1.1.1.1"

mkdir ~/.source
mkdir ~/.dotfiles
mkdir ~/.dots_global
mkdir ~/repos

sudo pacman -Sy bspwm sxhkd polybar

# Installing all packages in the pkglist.txt file.
sudo pacman --needed --ask 4 -Sy - < pkglist.txt || error "Failed to install required packages"

sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git ~/.source/paru
cd ~/.source/paru
makepkg -si
cd ~

echo "-----------------------------------"
echo "| Installing doom emacs, this can |"
echo "|         take a while            |"
echo "-----------------------------------"
sleep 2
[ -d ~/.emacs.d ] && mv ~/.emacs.d ~/.emacs.d.bak.$(date +"%Y%m%d_%H%M%S")
[ -f ~/.emacs ] && mv ~/.emacs ~/.emacs.bak.$(date +"%Y%m%d_%H%M%S")
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom --force install
~/.emacs.d/bin/doom sync

echo "-----------------------------------------------"
echo "Changing shell to bash"
sudo chsh $USER -s "/bin/bash"
echo "Reopen shell/Relogin for changes to take effect"
echo "-----------------------------------------------"

** Copy my configs
- drivers
  #+begin_src bash
  sudo pacman -S nvidia nvidia-utils intel-ucode
  #+end_src
- grub theme
- sddm theme
- bspwm and sxhkd
- eww widgets
- rofi
- polybar
- pacman and paru
  #+begin_src bash
  sudo sed -i "s/^#Color$/Color/" /etc/pacman.conf
  sudo sed -i "s/^#[multilib]$/[multilib]/" /etc/pacman.conf
  sudo sed -i "s/^#Include = /etc/pacman.d/mirrorlist$/Include = /etc/pacman.d/mirrorlist" /etc/pacman.conf
  sudo sed -i "s/^#BottonUp$/BottomUp/" /etc/paru.conf
  #+end_src

** Installation complete
echo "--------------------------"
echo "| Installation complete! |"
echo "--------------------------"
